name: simplify_lib
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/rzer/simplify_lib

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  event: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
